version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_PATH=/app/data/db.sqlite